### ISSUE TITLE
Installiert nicht auf 6.2.12

### ISSUE THREAD

**Issue by infabo** [move-elevator/me_extsearch#1]
Hallo Jan!

Leider installiert die Extension nicht auf 6.2.12.

![capture](https://cloud.githubusercontent.com/assets/3999104/7532249/0ad027d0-f565-11e4-92ac-86adb3d5e617.PNG)

Egal wie oft man Yes klickt, der Dialog kommt immer wieder.
Wenn man anschließend die Extension manuell im Ext-Manager aktiviert, dann erscheint folgende Fehlermeldung:

`Fatal error: Class 'MoveElevator\MeExtsearch\Utility\ExtensionSettingsUtility' not found in /var/www/.../vhosts/.../typo3conf/ext/me_extsearch/ext_localconf.php on line 12`

Install Tool:
![2015-05-08 09-37-55](https://cloud.githubusercontent.com/assets/3999104/7532344/08974e5c-f566-11e4-9f55-ace8743c03d2.png)

**Comment by janmaennig** [comment]
Hallo infabo!

vielen Dank für den Input. Wir haben den Fehler gefunden und beheben können. Die aktualisierte Version steht dir im TER zur Verfügung.
http://typo3.org/extensions/repository/view/me_extsearch

Viele Grüße
Jan
move : elevator
